# .github/workflows/e2e-ios.yml
name: e2e-ios
on: push

jobs:
  e2e-ios:
    runs-on: self-hosted
     env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    steps:

      - name: Install CocoaPods
        run: cd ios ; pod install ; cd -
